### ISSUE TITLE
How to uninstall VoodooHDA-2.8.8 Hackintosh High Sierra

### ISSUE THREAD

**Issue by ademir10** [chris1111/VoodooHDA-2.9.0-Clover-V11#2]
Hi Chris! how are you?
I'd like know how to uninstall VoodooHDA-2.8.8 from my hackintosh? Do you have some tool for that or some tutorial?

Thanks!

**Comment by chris1111** [comment]
How did you install VoodooHDA 2.8.8 ? because here its VoodooHDA 2.9.0

**Comment by ademir10** [comment]
Using a package .pkg and now I can’t remove pressing right button on panel preference, do you have any idea?

Ademir de Góes Gomes
Gerente de T.I / Consultor de Negócios

(11)4308-1643
(11)97039-5230
www.ddti.com.br  

Em 17 de abr de 2018, à(s) 11:09, chris1111 <notifications@github.com> escreveu:

**Comment by chris1111** [comment]
remove from System/Library/PreferencePanes ?
