### ISSUE TITLE
subwoofer not working 

### ISSUE THREAD

**Issue by maxis7567** [chris1111/VoodooHDA-2.9.0-Clover-V11#23]
acidanthera/AppleALC did it but has headphone noises. Can you bring it to voodoHda?
https://github.com/acidanthera/AppleALC/commit/d6a71e3a70aaf9331d25aaa2756dee77e38aa331

**Comment by chris1111** [comment]
Talk to the Devs
https://www.insanelymac.com/forum/topic/314406-voodoohda-295/
